In [1]:
import numpy as np
from keras.datasets import mnist
import tensorflow as tf
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import array_to_img
from sklearn.metrics import confusion_matrix


(X_train, y_train) , (X_test, y_test) =mnist.load_data() #Mnist verilerini çekme


In [2]:
#  VERİLERİ İŞLEM KOLAYLIĞI İÇİN 0-1 NORMALLEŞTİRME VE RESHAPE YAPMA
X_train = X_train / 255
X_test = X_test / 255
X_train = X_train.reshape(-1,28,28,1)    #training set
X_test = X_test.reshape(-1,28,28,1)      #test set


In [3]:
#MODEL OLUŞTURMA
from tensorflow.keras import models
from tensorflow.keras import layers
cnnModel = models.Sequential()

In [4]:
#KATMANLAR 
cnnModel.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(28,28,1)))
cnnModel.add(tf.keras.layers.MaxPooling2D((2, 2)))
cnnModel.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
cnnModel.add(tf.keras.layers.MaxPooling2D((2, 2)))
cnnModel.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
cnnModel.add(tf.keras.layers.MaxPooling2D((2, 2)))
cnnModel.add(tf.keras.layers.Flatten())
cnnModel.add(tf.keras.layers.Dense(32, activation='relu'))
cnnModel.add(tf.keras.layers.Dense(10, activation='softmax'))   

In [5]:
#MODELIN DERLENMESI VE EGITILMESI
cnnModel.compile(optimizer = 'rmsprop', loss= 'sparse_categorical_crossentropy',metrics=['accuracy'])
cnnModel.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 18s 9ms/step - loss: 0.2178 - accuracy: 0.9330
Epoch 2/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0735 - accuracy: 0.9781
Epoch 3/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0526 - accuracy: 0.9837
Epoch 4/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0414 - accuracy: 0.9874
Epoch 5/10
1875/1875 [==============================] - 20s 10ms/step - loss: 0.0350 - accuracy: 0.9897
Epoch 6/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0304 - accuracy: 0.9906
Epoch 7/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0253 - accuracy: 0.9926
Epoch 8/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.0225 - accuracy: 0.9938
Epoch 9/10
1875/1875 [==============================] - 20s 10ms/step - loss: 0.0197 - accuracy: 0.9947
Epoch 10/10
1875/1875 [==============================] - 20s 11ms

In [6]:
#MODEL TEST VE TRAİN SONUÇLARI
print("Model train data sonuçları Sonuçları")
cnnModel.evaluate(X_train, y_train)
print("Model test data sonuçları Sonuçları")
cnnModel.evaluate(X_test, y_test)

Model train data sonuçları Sonuçları
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0112 - accuracy: 0.9968
Model test data sonuçları Sonuçları
313/313 [==============================] - 1s 4ms/step - loss: 0.0616 - accuracy: 0.9877


[0.06160755455493927, 0.9876999855041504]

# Model test verilerinin tahminlerini alma

In [7]:
testTahminleri = cnnModel.predict(X_test)
print(testTahminleri[0])
print(F"TAHMİN SONUCU:{np.argmax(testTahminleri[0])}")
array_to_img(X_test[0])

[1.01614064e-11 1.33070770e-07 1.19105856e-07 1.22598365e-09
 7.65953132e-08 2.95166183e-11 1.63392073e-13 9.99999404e-01
 1.83807014e-08 2.73305574e-07]
TAHMİN SONUCU:7


In [8]:
#TEST TAHMİNLERİNİ INTE ÇEVİRME
testTahminleriInt=[]
for i in range(10000):
    testTahminleriInt.append(np.argmax(testTahminleri[i]))
testTahminleriInt=np.array(testTahminleriInt)
testTahminleriInt=testTahminleriInt.astype('uint8')

In [10]:
cm = confusion_matrix(testTahminleriInt,y_test)
print(cm)

[[ 968    0    1    0    0    2    2    1    0    4]
 [   1 1134    0    1    2    0    2    5    1    2]
 [   2    0 1018    2    0    0    0    5    2    0]
 [   0    0    0  993    0    3    0    1    2    0]
 [   0    0    1    0  970    0    3    0    1    7]
 [   2    0    1   11    0  884    2    2    0    6]
 [   2    0    0    0    3    2  947    0    0    0]
 [   1    1    9    2    1    1    0 1012    0    2]
 [   3    0    2    0    3    0    2    2  967    4]
 [   1    0    0    1    3    0    0    0    1  984]]


In [11]:
#MODELIN KAYIT EDILMESI
from tensorflow.keras.models import load_model
cnnModel.save("C:\\Users\\semih\\Desktop\\python\\Jupyter Notebook\\Bitirme Projesi\\model\\rakamTanimaModeli.h5")